### ISSUE TITLE
fillet not found

### ISSUE THREAD

**Issue by Thman558** [3xp10it/xwifi#4]
'/bin/sh: figlet: command not found
use noroot user run `brew install figlet`
Traceback (most recent call last):
  File "xwifi.py", line 23, in <module>
    figlet2file("xwifi", 0, True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/exp10it.py", line 1477, in figlet2file
    all_font_name_list = get_all_file_name(figlet_font_dir, ['tlf', 'flf'])
UnboundLocalError: local variable 'figlet_font_dir' referenced before assignment'

I tried running as root as well but same error
I am using python3

**Comment by lillois59** [comment]
> '/bin/sh: figlet: command not found
> use noroot user run `brew install figlet`
> Traceback (most recent call last):
> File "xwifi.py", line 23, in
> figlet2file("xwifi", 0, True)
> File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/exp10it.py", line 1477, in figlet2file
> all_font_name_list = get_all_file_name(figlet_font_dir, ['tlf', 'flf'])
> UnboundLocalError: local variable 'figlet_font_dir' referenced before assignment'
> 
> I tried running as root as well but same error
> I am using python3

Hi bro, if depend in which machine os you ran this script
